version: '3.9'
services:
  backend:
    build: .
    volumes:
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      - redis
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend
  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
